version: '3'

services:
  php:
    image: magento2.4:7.4-fpm
    build: ./config/php
    environment:
      COMPOSER_HOME: /var/www/html/.data/composer
      TZ: Europe/Berlin
    volumes:
      - .:/var/www/html:delegated,rw
    depends_on:
      - cache
      - elasticsearch
      - database

  elasticsearch:
    image: elasticsearch:7.8.0
    build: ./config/elasticsearch
    environment:
      discovery.type: 'single-node'
      xpack.security.enabled: 'false'
      xpack.monitoring.enabled: 'false'
      xpack.watcher.enabled: 'false'
    volumes:
      - .data/elasticsearch:/usr/share/elasticsearch/data:delegated
      - ./config/elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro

  cache:
    image: redis:latest

  database:
    image: mariadb/server:10.4
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: database
      MYSQL_ROOT_PASSWORD: password
      TZ: Europe/Berlin
    ports:
      - 3306:3306
    volumes:
      - .data/mysql:/var/lib/mysql:delegated

  frontend:
    image: nginx:1.16
    depends_on:
      - varnish
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./config/nginx/includes:/etc/nginx/includes
      - ./config/ssl:/etc/nginx/certs
      - ./config/nginx/frontend.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/html:delegated,ro
   
    networks:
      default:
        aliases:
          - magento.test
          
  backend:
    image: nginx:1.16
    depends_on:
     - php
    volumes:
      - .:/var/www/html:delegated,ro
      - ./config/nginx/includes:/etc/nginx/includes
      - ./config/nginx/backend.conf:/etc/nginx/conf.d/default.conf
      
  varnish:
    image: million12/varnish
    depends_on:
      - backend
    volumes:
      - ./config/varnish/default.vcl:/etc/varnish/default.vcl
      - .:/var/www/html:delegated,ro
    environment:
      VARNISHD_PARAMS: '-p http_resp_hdr_len=923648 -p http_resp_size=956416 -p workspace_backend=923648'
 

 